# Github Pages
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Setup
title:               Kai Fronsdal
tagline:             'AI Researcher'
description:         ''
url:                 https://kaifronsdal.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kai Fronsdal
  url:               https://kaifronsdal.github.io
  email:             kaifronsdal@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
