# Github Pages
lsi: false
safe: false
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Setup
title:               Kai Fronsdal
tagline:             'AI Researcher'
description:         ''
url:                 https://kaifronsdal.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
excerpt_separator: <!--more-->

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/
  projects:
    output: true
    permalink: /:categories/:title/

# About/contact
author:
  name:              Kai Fronsdal
  url:               https://kaifronsdal.github.io
  email:             kaifronsdal@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
